-- 테이블 간의 외래키 제약조건 해제team17
ALTER TABLE RETURN_HISTORY DROP FOREIGN KEY return_history_ibfk_1;
ALTER TABLE RETURN_HISTORY DROP FOREIGN KEY return_history_ibfk_2;

ALTER TABLE USAGE_PER_USER DROP FOREIGN KEY usage_per_user_ibfk_1;
ALTER TABLE USAGE_PER_USER DROP FOREIGN KEY usage_per_user_ibfk_2;

ALTER TABLE ECO_USAGE DROP FOREIGN KEY eco_usage_ibfk_1;

ALTER TABLE WORKOUT_USAGE DROP FOREIGN KEY workout_usage_ibfk_1;

ALTER TABLE BIKE_FIX DROP FOREIGN KEY bike_fix_ibfk_1;
ALTER TABLE BIKE_FIX DROP FOREIGN KEY bike_fix_ibfk_2;

ALTER TABLE TICKET DROP FOREIGN KEY ticket_ibfk_1;

ALTER TABLE MEMBER DROP FOREIGN KEY member_ibfk_1;

-- 테이블 삭제
DROP TABLE IF EXISTS TICKET, BIKE_FIX, BIKE_BREAKDOWN, WORKOUT_USAGE, ECO_USAGE, USAGE_PER_USER, USER, RETURN_HISTORY, RENT_HISTORY, BIKE_INFO_OF_STATION, MEMBER, STATION;
